#!/usr/bin/env bash
# this syntax codeblock will display numbers from 1 to 20 in addition to:
# "bad luck from China" displays on the 4th iteration
# "bad luck from Japan" displays on the 9th iteration
# "bad luck from Italy" displays on the 17th iteration

count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done
