#!/usr/bin/env bash

# this will display the exact 12 hour and 59 minutes time.
# after it will display the hours from 0 to 12
# lastly minutes will be displayed from 1 to 59


hour=0

while [ $hour -le 12 ]
do
  echo "Hour: $hour"
  minute=1
  while [ $minute -le 59 ]
  do
    echo "$minute"
    (( minute++ ))
  done
  (( hour++ ))
done
