#!/usr/bin/env bash
# this code will display the contents of the directory.
# it will only display the contents of the directory after the first dash

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
