#!/bin/bash

# Retrieve IPv4 addresses using 'ifconfig' command
ipv4_addresses=$(ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -d ' ' -f 2)

# Print the IPv4 addresses
echo "Active IPv4 addresses:"
echo "$ipv4_addresses"
